<template>
  <div
    class="
      h-[32px]
      p-[1px]
      rounded-[8px]
      bg-opact-gradient
      md:h-[30px]
      xl:h-[32px]
    "
  >
    <div
      class="
        h-full
        text-xs text-white
        px-[12px]
        rounded-[8px]
        bg-dark-blue
        flex
        items-center
        justify-center
        sm:text-[14px]
        sm:font-[500]
        sm:leading-[20px]
        sm:tracking-[0.1px]
        sm:px-[16px]
      "
    >
      <slot />
    </div>
  </div>
</template>
