<template>
  <LandingSection
    class="
      mb-[40px]
      md:mb-[60px]
      lg:mb-[70px]
      xl:mb-[80px]
      lg:!px-0
    "
  >
    <LandingContainer>
      <template
        v-slot:tag
      >
        <span
          class="
            block
            mb-[10px]
            sm:mb-[18px]
            lg:mb-[18px]
          "
        >
          Community
        </span>
      </template>

      <template
        v-slot:title
      >
        <span
          class="
            block
            mb-[6px]
            lg:max-w-full
            lg:mb-[10px]
            xl:mb-[6px]
            2xl:max-w-[455px]
          "
        >
          Connect with the Opact
          <span class="hidden md:inline">Wallet</span>
          community
        </span>
      </template>

      <template
        v-slot:text
      >
        <span
          class="
            block
            mb-[32px]
            sm:mb-[38px]
            lg:mb-[55px]
            xl:mb-[58px]
          "
        >
          Engage with the Opact Community
        </span>
      </template>

      <template
        v-slot:cta
      >
        <div
          class="
            flex
            space-x-[24px]
            lg:space-x-0
            xl:space-x-[24px]
            lg:flex-wrap
            xl:flex-nowrap
          "
        >
          <div
            class="
              w-[40px]
              h-[40px]
              bg-white
              rounded-full
              flex
              items-center
              justify-center
              text-dark-blue
              sm:w-auto
              sm:pl-[16px]
              sm:pr-[24px]
              sm:space-x-[8px]
              lg:mr-[24px]
              xl:mr-0
              lg:pl-[16px]
              lg:pr-[24px]
              lg:space-x-[8px]
              lg:h-[40px]
            "
          >
            <Icon name="github" />

            <div class="hidden sm:block">
              <p
                class="
                  text-[16px]
                  font-[500]
                  leading-[24px]
                  text-dark-blue
                  font-title
                  lg:text-[14px]
                  lg:font-[500]
                  lg:leading-[24px]
                  xl:text-[16px]
                  xl:font-[500]
                  xl:leading-[24px]
                "
              >
                Github
              </p>
            </div>
          </div>

          <div
            class="
              w-[40px]
              h-[40px]
              bg-white
              rounded-full
              flex
              items-center
              justify-center
              text-dark-blue
              sm:w-auto
              sm:pl-[16px]
              sm:pr-[24px]
              sm:space-x-[8px]
              lg:pl-[16px]
              lg:pr-[24px]
              lg:space-x-[8px]
              lg:h-[40px]
            "
          >
            <Icon name="discord" />

            <div class="hidden sm:block">
              <p
                class="
                  text-[16px]
                  font-[500]
                  leading-[24px]
                  text-dark-blue
                  font-title
                  lg:text-[14px]
                  lg:font-[500]
                  lg:leading-[24px]
                  xl:text-[16px]
                  xl:font-[500]
                  xl:leading-[24px]
                "
              >
                Discord
              </p>
            </div>
          </div>

          <div
            class="
              w-[40px]
              h-[40px]
              bg-white
              rounded-full
              flex
              items-center
              justify-center
              text-dark-blue
              sm:w-auto
              sm:pl-[16px]
              sm:pr-[24px]
              sm:space-x-[8px]
              lg:mt-[24px]
              xl:mt-0
              lg:pl-[16px]
              lg:pr-[24px]
              lg:space-x-[8px]
              lg:h-[40px]
            "
          >
            <Icon name="twitter" />

            <div class="hidden sm:block">
              <p
                class="
                  text-[16px]
                  font-[500]
                  leading-[24px]
                  text-dark-blue
                  font-title
                  lg:text-[14px]
                  lg:font-[500]
                  lg:leading-[24px]
                  xl:text-[16px]
                  xl:font-[500]
                  xl:leading-[24px]
                "
              >
                Twitter
              </p>
            </div>
          </div>
        </div>
      </template>
    </LandingContainer>
  </LandingSection>
</template>
