<template>
  <figure>
    <NuxtImg
      src="/site-bg.png"
      class="
        absolute
        top-[-190px]
        sm:top-[-40px]
        left-1/2
        z-[-1]
        min-w-[1364px] min-h-[880px]
        -translate-x-1/2
        pointer-events-none
        select-none
      "
      sizes="2560:1364px"
    />
  </figure>
</template>
