export const nuxtIcon = {
  aliases: {
    eth: 'Eth',
    near: 'Near',
    menu: 'Menu',
    logo: 'Logo',
    arrow: 'Arrow',
    close: 'Close',
    github: 'Github',
    kadena: 'Kadena',
    logout: 'Logout',
    meteor: 'Meteor',
    ecko: 'EckoWallet',
    twitter: 'Twitter',
    discord: 'Discord',
    spinner: 'Spinner',
    chevron: 'Chevron',
    airplane: 'Airplane',
    security: 'Security',
    walletConnect: 'WalletConnect',
    opactLogo: 'OpactLogo',
    receiptSend: 'SendReceipt',
    receiptReceive: 'ReceiveReceipt',

    // App Icons
    qr: 'QR',
    ring: 'Ring',
    active: 'Active',
    pen: 'Pen',
    add: 'Add',
    copy: 'Copy',
    edit: 'Edit',
    list: 'List',
    send: 'Send',
    radio: 'Radio',
    share: 'Share',
    chart: 'Chart',
    search: 'Search',
    filter: 'Filter',
    hidden: 'Hidden',
    blocks: 'Blocks',
    wallet: 'Wallet',
    visible: 'Visible',
    receive: 'Receive',
    iconSettings: 'IconSettings',
    calendar: 'Calendar',
    arrowRight: 'ArrowRight',
    radioActive: 'RadioActive',
    information: 'Information',
    chevronLeft: 'ChevronLeft',
    minilogo: 'MiniLogo',
    notification: 'Notification'
  }
}

export default nuxtIcon
