version: '3.9'

# For usage instructions please take a look at the README.md file.
networks:
  indexer: {}

volumes:
  pg_data:

services:
  chainweb-data:
    expose:
      - "8888"
    ports:
      - "8888:8888"
    build:
      dockerfile: ./src/Dockerfile
    env_file:
      - .env
    networks:
      - indexer

  postgresql:
    image: postgres:14.5-bullseye
    user: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./src/scripts/init-database.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - indexer

  # ########################################################################## #
  # Debugging

  debug:
    image: alpine:latest
    entrypoint:
    - /bin/sh
    profiles:
    - debug
