name: CI
on: pull_request

jobs:
  frontend_dev_deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
      GTM_TAG: ${{ vars.GTM_TAG }}
      SDK_NETWORK: ${{ env.SDK_NETWORK }}
      WC_RELAYER: ${{ env.WC_RELAYER }}
      WC_PROJECT_ID: ${{ env.WC_PROJECT_ID }}
      FAUCET_DISABLED: true
      NFT_DISABLED: true
      IS_PROD: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Pull vercel setup
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        env:
          NITRO_PRESET: vercel
        run: vercel build

      - name: Deploy Project Artifacts to Vercel
        run: >
          vercel
          deploy
          --prebuilt
          --token=${{ secrets.VERCEL_TOKEN }}
