name: Terraform Deployment

on:
  repository_dispatch:
    types: [terraform-sync-command]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.TERRAFORM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.TERRAFORM_SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: pnpm install

      - name: Install Dependencies
        run: pnpm indexer api package

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - uses: pnpm/action-setup@v2
        with:
          version: 8.1.0

      - name: Create .tfvars file
        run: |
          echo "db_password=\"${{ secrets.DB_PASSWORD }}\"" >> ./terraform/.tfvars
          echo "aws_access_key=\"${{ secrets.AWS_ACCESS_KEY }}\"" >> ./terraform/.tfvars
          echo "aws_secret_key=\"${{ secrets.AWS_SECRET_KEY }}\"" >> ./terraform/.tfvars
          echo "" >> ./terraform/.tfvars

      - name: Terraform Init
        run: pnpm terraform init-terraform

      - name: Terraform Plan
        run: pnpm terraform plan

      - name: Terraform Apply
        run: pnpm terraform apply
